name: Build and deploy ASP.Net Core app to Azure Web App - icmet

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore
        run: dotnet restore src/Backend/Institute.Web/Institute.Web.sln

      - name: Build
        run: dotnet build src/Backend/Institute.Web/Institute.Web.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish src/Backend/Institute.Web/Institute.API/Institute.API.csproj --configuration Release --output "${{ github.workspace }}/publish" --no-build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/publish

  deploy:
    runs-on: windows-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_737438DAEFB4472485E6BAB17BAF84DE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CE95D38C24E64B91BD58616839EF32F9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C911F079DD4F4EA68F5F80B51E7DD99A }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'icmet'
          slot-name: 'Production'
          package: ./publish
